# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Build, Deploy, and Upload Artifacts

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - feature-1
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Java
      - name: Set up Java
        uses: actions/setup-java@v3

      # Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: 
          
      # Build the project with Maven
      - name: Build with Maven
        run: mvn clean install

      # Upload the WAR as an artifact using v4
     # - name: Upload WAR file to Artifactory
     #   run: |
     #     curl -u "${{ secrets.ARTIFACTORY_USERNAME }}:${{ secrets.ARTIFACTORY_API_KEY }}" -T "target/simple-parcel-service-app-1.0-SNAPSHOT.war" "https://trialvvjw1c.jfrog.io/artifactory/my-hello-world-new-libs-snapshot/com/jfrog/my-jfrog-app/my-parcel-service-war-${{ github.run_number }}.war"
